Neovim and Tmux improvements
lfilho/dotfiles pull request #34
Opened 2021-07-12 19:44 UTC by nandalopes

- style(nvim): group together colorschemes
- feat(nvim): allow local plugins
- fix(nvim): powerline extended symbols
- feat(nvim): OS specific keymaps
- style(nvim): align comments on plugin set
- refactor(tmux): many improvements

2021-07-14 03:27 UTC, lfilho requested changes
Hey! Thanks for the contribution!! 💪 

Apart the questions/comments I posted on the diff view, it looks likes there's a some new things, other things being changed, but you haven't documented / explained them here in the PR description. That alongside the several changes in indentation, spaces and styles, makes it really hard to review the PR.

I'd personally recommend not to change styles like that unless we can make it as part of automatic linting/tooling, otherwise it becomes a matter of personal taste (then next person sending a PR will change it to something THEY like, so on so on...).

If you insist on changing the style, at least comment on each diff what is actually changing / new versus just style changes.

2021-07-14 03:27 UTC, lfilho commented on nvim/plugins/improvements.vim
> -
The diff is hard to pass now. Is this just changing some of the order the comments' indentation?

2021-07-14 03:27 UTC, lfilho commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
We already support this. Check the the before/main and after/main files. The comments in there explain it. nvim/README also documents and explains this...

2021-07-14 03:27 UTC, lfilho commented on nvim/settings/plugin-lightline.vim
> +   \ 'separator': { 'left': '', 'right': '' },
What are these glyphs? Could you paste an screenshot of how it looks? Thanks

2021-07-14 03:27 UTC, lfilho commented on tmux/tmux.conf
> +bind-key -T edit-mode-vi Up send-keys -X history-up
Just checking: did you test these bindings to make sure the space between `T` and, for example, `copy-mode` is ok? I thought it was needed (at least that's how i've seen in other dotfiles as well)

2021-07-14 03:27 UTC, lfilho commented on nvim/settings/vim-keymaps-linux.vim
> +" ========================================
This and the file below looks like it was supposed to be just renaming files, right? But here they show as new ones (the deleted ones are not here). So it seems something went wrong when renaming/committing them to git.

2021-07-14 03:34 UTC, lfilho requested changes

2021-07-14 03:34 UTC, lfilho commented on .gitignore
> +nvim/.local.vim
See comment below, not needed

2021-07-14 03:34 UTC, lfilho commented on nvim/settings/after/colorscheme.vim
> +let g:lightline.colorscheme='gruvbox'
We have this line here: https://github.com/lfilho/dotfiles/blob/master/nvim/settings/plugin-lightline.vim#L2
The idea is to leave all plugin config in their `plugin-*` file so if we need to change a certain config in the future, we know for sure they will be there. Also, if we decided to remove/replace a plugin, we know all we have to do is to remove that file.

2021-07-14 03:34 UTC, lfilho commented on nvim/settings/main.vim
> -    if (fpath == expandedSettingsPath . "/yadr-keymap-mac.vim") && uname[:4] ==? "linux"
I like the change but see my other comment below: it looks like the actual renaming of files didn't work on git.

2021-07-14 03:34 UTC, lfilho commented on tmux/tmux.conf
> +# Screen like binding
There are a lot of new bindings, changing old bindings, etc on this file. Please provide your reasoning why we should change them for everybody (as this would be a breaking change). Otherwise (if it's just your personal preference), please do it on the local files instead. :)

2021-07-14 05:26 UTC, nandalopes reviewed
I'm sorry for this mono-PR. I comment on commits the changes.

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +bind-key -T edit-mode-vi Up send-keys -X history-up
yep ;-)

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +
It's a new but quite common bind in dotfiles...

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +set -g renumber-windows on
Other quite common adition: renumber windows after closing one in the midle.

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +set-option -ga status-style bg=colour237,fg=colour223 #bg=bg1 fg=fg1
I don't remember the tmux version when style directives have changed, but there's been a while for sure.

I've tested this config with the version in Ubuntu Bionic, 2.6.3, and -bg/-fg was already changed to -style there.

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +bind C-l send-keys C-l
`prefix + Control-l` clear screen, but `Control + l` behaves like before and select pane at right

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"
This is from tmux-navigator plugin help and I've been using for a long time.

2021-07-14 05:26 UTC, nandalopes commented on tmux/tmux.conf
> +# Screen like binding
I've moved the prefix bind up for readability, but seeing filelog the `last screen bind` have changed to upstream `C-b`

2021-07-14 05:26 UTC, nandalopes commented on nvim/settings/main.vim
> -    if (fpath == expandedSettingsPath . "/yadr-keymap-mac.vim") && uname[:4] ==? "linux"
It's because there's no yadr-keymap-{mac,linux}.vim at your repo.

2021-07-15 12:18 UTC, nandalopes commented
Tmux improvements:

- Highlight window name with purple bold font when zoomed
- Renumber windows
- Separate colorscheme from other styling settings
- Use `none` style attribute instead of `nobold,noitalic,...`
- Restore clear screen keybind mapped over by tmux-navigator
  - C-l changes pane
  - Prefix + C-l clear screen

Neovim improvements:

- Use nerdfonts powerline glyphs
- Source local plugins commands at `plugins/main.vim`, before plug#end()

2021-07-17 15:44 UTC, lfilho commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
But we actually can install custom plugins in the current after files, right? So my question is why do we need a second way of accomplishing that..?

2021-07-17 16:59 UTC, nandalopes commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
No we don't, unless we add another .vim in plugins folder, and that file will be tracked anyway.

2021-07-20 00:33 UTC, lfilho commented on nvim/plugins/improvements.vim
> -
Unless there's a plugin automatically indenting the comments like this, I would prefer to leave as they were before otherwise it would be tiresome to keep maintaining and changing spacing around them. So could you please either provide that auto-formatting support or keep the previous commenting style? Thanks!

2021-07-20 00:33 UTC, lfilho commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
What I mean is that we can add a `Plug install <bla>` in the `after` file and it would work to install plugins, wouldn't it?
Also, it's best to let the author of a comment resolve that thread instead of resolving it ourselves 😇

2021-07-20 23:25 UTC, nandalopes commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
No, unfortunately we can't do this =(

Oops, sorry I misunderstood the resolv button...

2021-07-20 23:28 UTC, nandalopes commented on nvim/plugins/improvements.vim
> -
Yes there is Tabular, in improvements bundle

2021-07-21 15:13 UTC, lfilho commented on nvim/plugins/improvements.vim
> -
But is not automatically formatting the file, right?

2021-07-21 15:53 UTC, nandalopes commented on nvim/plugins/improvements.vim
> -
No, it's not like an autocmd, but can be easily triggered using the plugin included (Tabularize)

2021-07-22 02:48 UTC, lfilho commented on nvim/plugins/improvements.vim
> -
Exactly, that's my point: if we don't have an automatic way to guarantee formatting, better not to change it. Otherwise here's what happens:

1. There's one personal cosmetic preference currently (mine)
2. You send a big diff with your own personal preference (this PR)
3. From now on me and future contributors have to adjust and remember to use `Tabularize` in those files (extra annoying manual work)
4. A future contributor don't like your personal preference from step 2 and sends a big PR to either revert it back to the way it was on step 1 or worse, proposes a 3rd way 😓 
5. The cycle repeats, including this very conversation 😄 

It's 2021, styling/formatting shouldn't be done manually. If there's not a way to make the auto-formatting work or if it's not worth the effort, then the recommendation when contributing to an existing project is to leave as it is when you found and follow the repo's current style in order to avoid unnecessary diffs and discussions around personal preferences. Makes sense?

2021-07-22 02:51 UTC, lfilho commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
Hmm have you actually tested it? I have just tested it and it works:

1. created `~/.yadr/nvim/settings/after/test.vim`
2. added `Plug 'pineapplegiant/spaceduck', { 'branch': 'main' }` in it (it's a colorscheme)
3. ran `:PlugInstall`
4. ran `:colors spaceduck`
5. Worked, without the `test.vim` being tracked

2021-07-22 02:54 UTC, lfilho commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
Maybe you missed this? https://github.com/lfilho/dotfiles/blob/50db8ba18db1cc4cf03af787d87d9c241e5bcd2f/.gitignore#L18-L21

2021-07-22 12:00 UTC, nandalopes commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
It installs the plugin, but it doesn't get loaded after restarting nvim:

```
Erro detectado ao processar /home/nanda/.dotfiles/neovim/settings/after/colorscheme.vim:
linha   10:
E185: Esquema de cores 'spaceduck' não encontrado
```

2021-07-22 12:21 UTC, nandalopes commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
Adendum: it's not necessary to explicit load .local.vim on plugins/main.vim, but is mandatory to load Plug there, otherwise you won't get the plugin after restarting nvim.

2021-08-02 18:31 UTC, lfilho commented on nvim/plugins/main.vim
> +" The plugins listed in ~/.config/nvim/.local.vim will be added here to
Yes, that's correct. That's the default behavior. Upon installing we do manually trigger Plug so it can install the plugins, though. Anything post-install needs to have an explicit call to PlugInstall.

But I'm confused why you brought that up, that would also happen with your proposed changes, right?

2021-08-03 15:49 UTC, nandalopes commented on .gitignore
> +nvim/plugins/*.vim
Actually git remains aware of changes in files that are already added.
Any change in the files on repo will be noticed, only tools that use .gitignore patterns to exclude search will be affected, like ripgrep without `--no-vcs-ignore` opt.

2021-08-06 18:40 UTC, lfilho commented on .gitignore
> +nvim/plugins/*.vim
Yes, but what if we want to add a new plugin (e.g.: right now i have a `coc` branch and in the future i might merge it in, in that case the new files in there wouldn't get tracked and my changes would stay local to my machine)?

What benefits did you have in mind by adding this here? I am not seeing them yet, only the issue i highlight above :)

2021-08-06 20:20 UTC, nandalopes commented on .gitignore
> +nvim/plugins/*.vim
For example, at work I manage some PHP files, but I don't want to add a PHP bundle on personal computer.

At home I use vimwiki, but not at work., and so on.

I have a work branch, which I've forced add a web.vim bundle, with `git add -f <file>`, and a local_bundles.vim file at home, not tracked, with vimwiki.

2021-08-08 00:00 UTC, lfilho commented on .gitignore
> +nvim/plugins/*.vim
Got it. I still don't see a big reason to do it, but I guess it doesn't hurt to try. Will merge. Thanks again for the nice contributions! I'm about to push some more as well

2021-08-08 00:02 UTC, merged